/*
 * This source file was generated by the Gradle 'init' task
 */
package org.linesOfAction;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.linesOfAction.gui.LinesOfActionGui;

public class App {

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        LinesOfActionGui board = new LinesOfActionGui();
        board.setVisible(true);
    }
}